spring:
  application:
    name: todo
  liquibase:
    change-log: classpath:db/migration/V1__Create_tasks_table.sql
  profiles:
    active: test
  logging:
    level:
      root: DEBUG
      org.springframework.web: DEBUG
      liquibase: DEBUG
  jpa:
    generate-ddl: true
    show-sql: true
    open-in-view: false
    output:
      ansi:
        enabled: always
    hibernate:
      ddl-auto: update