spring:
  application:
    name: todo
  liquibase:
    change-log: classpath:db/migration/V1__Create_tasks_table.sql
  profiles:
    active: test
  logging:
    level:
      root: DEBUG
      org.springframework.web: DEBUG
      liquibase: DEBUG
hibernate:
  connection:
    url: jdbc:postgresql://db:5432/springjdbc
    username: admin
    password: qwerty
  show_sql: true
  format_sql: true
  highlight_sql: true
  hbm2ddl:
    auto: create